# .mergify.yml updated pr
queue_rules:
  - name: default
    merge_conditions:
      - check-success=ci-test

pull_request_rules:
  - name: queue PRs automatically
    conditions:
      - base=main
      - check-success=ci-test
    actions:
      queue:
        name: default
